[package]
name = "ethereum-core"
edition = "2021"
version.workspace = true

[dependencies]
adapter_sdk = { path = "../../../adapter_sdk", default-features = false, optional = true }
nexus-core = { path = "../../../core", default-features = false, optional = true }
anyhow = { workspace = true }
#helios = { git = "https://github.com/a16z/helios", version = "0.8.3" }
helios-consensus-core = { git = "https://github.com/a16z/helios", version = "0.8.1" }
tree_hash = "0.9.0"
alloy = { version = "0.9.1", features = [
    "rpc-types",
    "consensus",
    "rlp",
    "k256",
    "provider-http",
    "sol-types",
    "network",
    "ssz",
    "json-rpc",
    "signers",
] }
serde_cbor = "0.11.2"
serde = { workspace = true, features = ["derive"] }
alloy-sol-types = { workspace = true }

[features]
default = ["risc0"]
zkvm-risc0 = ["nexus-core/zkvm-risc0", "adapter_sdk/zkvm-risc0"]
zkvm-sp1 = ["nexus-core/zkvm-sp1", "adapter_sdk/zkvm-sp1"]
risc0 = ["nexus-core/native-risc0", "adapter_sdk/native-risc0", "native"]
sp1 = ["nexus-core/native-sp1", "adapter_sdk/native-sp1", "native"]
native = ["nexus-core/native"]
zkvm-risc0-cuda = ["nexus-core/native-risc0-cuda", "adapter_sdk/zkvm-risc0-cuda"]