[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
avail-core = { git = "https://github.com/availproject/avail-core.git", branch = "toufeeq/scalable-da-2" }
kate = { git = "https://github.com/availproject/avail-core.git", branch = "toufeeq/scalable-da-2" }
kate-recovery = { git = "https://github.com/availproject/avail-core.git", branch = "toufeeq/scalable-da-2" }
hex = "0.4.3"
anyhow = "1.0.96"
bls12_381 = { version = "0.8.0", default-features = false, features = [
  "groups",
  "pairings",
  "alloc",
] }
ff = { version = "0.13.0", default-features = false, features = ["derive"] }
ark-ff = { version = "0.4.0-alpha.7", default-features = false }
