[package]
name = "sp1_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
zksync-methods = { path = ".." } 
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git"}
nexus-core = { path = "../../../../core", default-features = false, features = ["zkvm-risc0"]}


