[package]
name = "sp1_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
nexus-core = { path = "../../../../core", default-features = false, features = ["zkvm-risc0"]}
adapter_sdk = { path = "../../../../adapter_sdk", default-features = false, features = ["zkvm"] }
zksync-core = { path = "../../core", default-features = false, features = ["zkvm"] }
zksync-methods = { path = ".." } 
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git"}
bincode = "1.3"
