[package]
name = "zksync-adapter-sp1"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
nexus-core = { path = "../../../../core", default-features = false, features = ["zkvm-sp1"] }
zksync-core = { path = "../../core", default-features = false, features = ["zkvm-sp1"] }
sp1-zkvm = { version = "3.4.0"}
sp1-derive = { version = "3.4.0"}