[package]
name = "zksync-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0.1" }

[package.metadata.risc0]
methods = ["risc0_guest","sp1_guest"]

[features]
sp1 = []