[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
prover = { path = "../prover" }
risc0-zkvm = { version = "0.20.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
nexus-core = { path = "../../core"}
serde_json = "1.0.114"
tokio = "1.36.0"
sp-runtime = "33.0.0"
parity-scale-codec = { version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
relayer = { path = "../../relayer" }
anyhow = "1.0.80"
warp = "0.3.6"
