[package]
name = "ethereum_adapter_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
helios-consensus-core = { workspace = true }
sp1-helios-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
tree_hash = { workspace = true }
nexus-core = { path = "../../../../core", default-features = false, features = [
  "zkvm-risc0",
] }
serde_cbor = "0.11.2"
