[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.1", optional = true }
sp1-build = { version = "3.4.0", optional = true }

[package.metadata.risc0]
methods = ["risc0-guest"]

[features]
sp1 = ["sp1-build"]
risc0 = ["risc0-build"]
