[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"

[profile.solc]
version = "0.8.21"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
zksync_era1 = "${ZKSYNC_ERA1_RPC_URL}"
zksync_era2 = "${ZKSYNC_ERA2_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
