[package]
name = "ethereum-adapter-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
nexus-core = { path = "../../../../core", default-features = false, features = [
    "zkvm-sp1",
] }
sp1-zkvm = { version = "3.4.0" }
sp1-derive = { version = "3.4.0" }
ethereum-adapter-core = { path = "../../ethereum_adapter_core", default-features = false, features = ["zkvm-sp1"] }