[package]
name              = "ethereum-adapter"
version.workspace = true
edition           = "2021"

[dependencies]
risc0-zkvm = { version = "2.0.0", default-features = false, features = [
    'std',
] }
nexus-core = { path = "../../../../core", default-features = false, features = [
    "zkvm-risc0",
] }
ethereum-core = { path = "../../core", default-features = false, features = [
    "zkvm-risc0",
] }
