[package]
name = "adapter_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.36.0"
hex = "0.4"
tokio-stream = "0.1.14"
reqwest = {version = "0.11.24", features = ["json"]}
avail-subxt = { git = "https://github.com/availproject/avail.git", tag = "v1.11.0.0", features = ["std"], optional = true }
henosis = { git = "https://github.com/Banana-Wallet/Henosis.git", rev = "2b693c6" }
converter = { git = "https://github.com/Banana-Wallet/Henosis.git", rev = "2b693c6" }
nexus-core = { path = "../core", features = ["zkvm"]}
num-bigint = "0.4.4"
ckb-types = "0.114.0"
sparse-merkle-tree = { git = "https://github.com/vibhurajeev/sparse-merkle-tree.git", default-features = false }
serde = "1.0.196"
serde_json = "1.0.113"
risc0-zkvm = {version = "0.20.1", features = ["std"], default-features = false }
anyhow = "1.0.81"

[patch.crates-io]
sp-core = { git = "https://github.com/availproject/substrate.git", branch = "goldberg" }
sp-io = { git = "https://github.com/availproject/substrate.git", branch = "goldberg" }
sp-runtime = { git = "https://github.com/availproject/substrate.git", branch = "goldberg" }
sp-std = { git = "https://github.com/availproject/substrate.git", branch = "goldberg" }
sp-core-hashing = { git = "https://github.com/availproject/substrate.git", branch = "goldberg" }
