name: Contract Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install RISC0 toolchain
        run: |
            curl -L https://risczero.com/install | bash
            echo "${HOME}/.risc0/bin" >> $GITHUB_PATH
            # Need to install for specific version next.
            ${HOME}/.risc0/bin/rzup install
            ${HOME}/.risc0/bin/rzup install cargo-risczero 1.2.0

      - name: Build Contract Artifacts
        run: |
          cd examples/mock_geth_adapter
          cargo build --release
          cd ../examples/zksync_adapter
          cargo build --release

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run tests
        run: forge test -vvv