name: E2E Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true
      ACTIONS_STEP_DEBUG: false
      RUNNER_DEBUG: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Free Disk Space
        run: |
          echo "Before cleanup:"
          df -h
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune --all --force --volumes
          echo "After cleanup:"
          df -h

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install RISC0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          echo "${HOME}/.risc0/bin" >> $GITHUB_PATH
          # Need to install for specific version next.
          ${HOME}/.risc0/bin/rzup install
          ${HOME}/.risc0/bin/rzup install cargo-risczero 1.2.0

      - name: Build binaries
        run : |
            cd nexus/host
            cargo build --bin node --no-default-features --features "risc0"
            cd ../../examples/mock_geth_adapter/host
            cargo build

      - name: Run avail node
        run: |
          docker pull ocdbytes/availnode:latest
          mkdir output
          docker run --rm -p 30333:30333 -p 9944:9944 -v ./output:/output ocdbytes/availnode:latest --dev --rpc-methods=unsafe --unsafe-rpc-external --rpc-cors=all &

      - name: Run integration tests
        run: |
          cd integration
          RISC0_DEV_MODE=true cargo test