name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          override: true

      - name: Install RISC0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          echo "${HOME}/.risc0/bin" >> $GITHUB_PATH
          # Need to install for specific version next.
          ${HOME}/.risc0/bin/rzup install
          ${HOME}/.risc0/bin/rzup install cargo-risczero v1.2.0

      - name: Run integration tests
        run: |
          cd nexus/host/
          RISC0_DEV_MODE=true cargo test