name: E2E Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true
      ACTIONS_STEP_DEBUG: false
      RUNNER_DEBUG: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Free Disk Space
        run: |
          echo "Before cleanup:"
          df -h
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune --all --force --volumes
          echo "After cleanup:"
          df -h

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install RISC0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          echo "${HOME}/.risc0/bin" >> $GITHUB_PATH
          # Need to install for specific version next.
          ${HOME}/.risc0/bin/rzup install

#TODO: Run a local avail devnet once there is an infinity devnet release. Currently we use a deployment for the tests.
      - name: Build binaries
        run : |
            cd nexus/host
            cargo build --bin node --no-default-features --features "risc0"
            cargo build --bin prover --no-default-features --features "risc0"
            cd ../../examples/mock_geth_adapter/host
            cargo build

      - name: Setup Database
        run: |
            docker run --name my-postgres \
              -e POSTGRES_USER=user \
              -e POSTGRES_PASSWORD=password \
              -e POSTGRES_DB=db_name \
              -p 5432:5432 \
              -d postgres:17

            export DATABASE_URL=postgres://user:password@localhost:5432/db_name

            cd core
            cargo install sqlx-cli --no-default-features --features native-tls,postgres
            sqlx migrate run
            cargo sqlx prepare -- --lib --features native

      - name: Run integration tests
        run: |
          cd integration
          RISC0_DEV_MODE=true cargo test