name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RISC0_DEV_MODE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          override: true

      - name: Install RISC0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          ~/.cargo/bin/rzup install cargo-risczero v1.1.1
          echo "${HOME}/.risc0/bin" >> $GITHUB_PATH
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Verify RISC0 toolchain installation
        run: |
          ~/.risc0/bin/risc0 --version
          ~/.cargo/bin/rzup list

      - name: Run integration tests
        run: |
          cd nexus/host/
          RISC0_DEV_MODE=true cargo test